name: Branch Quality Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14.15.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
      - run: yarn install
      - run: yarn build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14.15.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
      - run: yarn install
      - run: yarn test
